name = "api-dev"
main = "src/index.ts"
compatibility_date = "2022-08-19"
usage_model = "bundled"
account_id = "ae6e658c037606bf7536325a439f3456"
minify = true
workers_dev = true
vars = {ACCOUNT_ID = "ae6e658c037606bf7536325a439f3456"}

[env.production]
name = "api"
workers_dev = false
route = "sparky.works/api*"
vars = {ACCOUNT_ID = "ae6e658c037606bf7536325a439f3456"}