name = "api"
main = "src/index.ts"
compatibility_date = "2022-08-19"
usage_model = "bundled"
account_id = "ae6e658c037606bf7536325a439f3456"
minify = true

[vars]
ACCOUNT_ID = "ae6e658c037606bf7536325a439f3456"

[env.dev]
workers_dev = true

[env.production]
workers_dev = false
route = "sparky.works/api*"