name = "sticker-pack-replicator"
main = "dist/worker.js"
compatibility_date = "2022-08-24"

account_id = "ae6e658c037606bf7536325a439f3456"
usage_model = "bundled"
workers_dev = false
vars = { ENVIRONMENT = "dev", SPARKY_TELEGRAM_ID = "728854954" }
route = "dev.sticker-replicator.sparky.works/*"

[build]
command = "npm run build"

[env.production]
workers_dev = false
name = "sticker-pack-replicator-production"
vars = { ENVIRONMENT = "production", SPARKY_TELEGRAM_ID = "728854954" }
routes = [
  "sticker-replicator.sparky.works/*"
]